name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # Checkout the repo
      - uses: actions/setup-python@v5     # Setup Python environment
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt  # Install dependencies
      - run: pip install pytest              # Install pytest
      - run: pytest tests/ -v                  # Run tests

  deploy:
    runs-on: ubuntu-latest
    needs: test                        # Only run if tests pass
    if: github.event_name == 'push'   # Only on push, not PR
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true                     # Enable Git LFS

      - name: Deploy to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git assets notebooks data
          git init
          git lfs install
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f models/fraud_detection_v1_xgb.pkl
          git add .gitattributes app.py src/ models/ params.yaml requirements.txt Dockerfile README.md
          git commit -m "deploy: production release v1 with LFS"
          git remote add space https://renteria-luis:$HF_TOKEN@huggingface.co/spaces/renteria-luis/fraud-detection-v1
          git push space master:main --force  # Push to Hugging Face Space